"""
Django settings for new_seite project.

Generated by 'django-admin startproject' using Django 3.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-o7%cc6o2bsvq9x9drrgfy&l+d!xjf59oa!q57+q)4)_@x4q9*8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [] # '%' - wenn DEBUG False, bei True nicht nötig


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'news',
    'numis',


]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# stand ori drin ROOT_URLCONF = 'new_seite.urls' # funkt - ROOT_URLCONF = 'news.urls' - NEU
ROOT_URLCONF = 'new_seite.urls' # zwar fehler aber /meldungen hat dann gefunkt - NEU falls probleme auftreten

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [], # original vor templates implement
        'DIRS': [os.path.join(BASE_DIR, 'new_seite', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'new_seite.wsgi.application'


"""
# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
# meine START
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # 'host',
        'NAME': 'db66665', # 'DB_name',
        'HOST': 'mysql07.manitu.net', # '127.0.0.1', # '127.0.0.1',
        'PORT': '3306',
        'USER': 'u66665', # 'root', # 'DB_user',
        'PASSWORD': 'Bzz2YUhEsRmrGxPA', # 'Bzz2YUhEsRmrGxPA', # 'DB_password',
    }
}
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql', # 'host',
        'NAME': 'db66847', # 'DB_name',
        'HOST': 'mysql06.manitu.net', # '127.0.0.1', # '127.0.0.1',
        'PORT': '3306',
        'USER': 'u66847', # 'root', # 'DB_user',
        'PASSWORD': '22vvuDBhpDVmNXfz', # 'Bzz2YUhEsRmrGxPA', # 'DB_password',
    }
}
# meine ENDE



# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'de-DE' # en-us - neu

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False # True - neu


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
