# Generated by Django 3.0.3 on 2021-05-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210519_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meldung',
            name='text',
            field=models.TextField(verbose_name='werde ich als Klasse automatisch übertragen oder muss ich mikrieren'),
        ),
    ]
