# Generated by Django 3.0.3 on 2021-05-20 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210520_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='tab_20',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wahrung', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tab_30',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tab_40',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tab_50',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.CharField(max_length=1)),
                ('proDescribe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tab_70',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollDescribe', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=2)),
            ],
        ),
    ]
