# Generated by Django 3.2.3 on 2021-05-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20210521_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tab_10',
        ),
        migrations.DeleteModel(
            name='tab_20',
        ),
        migrations.DeleteModel(
            name='tab_30',
        ),
        migrations.DeleteModel(
            name='tab_40',
        ),
        migrations.DeleteModel(
            name='tab_50',
        ),
        migrations.DeleteModel(
            name='tab_70',
        ),
    ]
