# Generated by Django 3.2.3 on 2021-05-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tab_10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.BigIntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tab_20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wahrung', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tab_30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='tab_40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.BigIntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='tab_50',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produce', models.CharField(max_length=1)),
                ('proDescribe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tab_60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgFrond', models.CharField(max_length=100)),
                ('imgBack', models.CharField(max_length=100)),
                ('edge', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=200)),
                ('value', models.BigIntegerField(max_length=6)),
                ('mKey', models.CharField(max_length=10)),
                ('unit', models.BigIntegerField(max_length=2)),
                ('wahrung', models.CharField(max_length=5)),
                ('land', models.CharField(max_length=50)),
                ('year', models.BigIntegerField(max_length=4)),
                ('produce', models.CharField(max_length=1)),
                ('pollution', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='tab_70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pollDescribe', models.CharField(max_length=50)),
                ('key', models.CharField(max_length=2)),
            ],
        ),
    ]
