# Generated by Django 3.2.3 on 2021-05-25 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0002_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaultValueForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultValue', models.BigIntegerField(max_length=20)),
            ],
        ),
    ]
