# Generated by Django 3.2.3 on 2021-05-25 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0004_auto_20210525_0135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defaulti',
            new_name='DefaultWerteForms',
        ),
    ]
