# Generated by Django 3.2.3 on 2021-05-25 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0005_rename_defaulti_defaultwerteforms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultWerteForms',
            new_name='FormsDefault',
        ),
    ]
