# Generated by Django 3.2.3 on 2021-05-25 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0006_rename_defaultwerteforms_formsdefault'),
    ]

    operations = [
        migrations.CreateModel(
            name='numis_defaulti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultValue', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='FormsDefault',
        ),
    ]
