# Generated by Django 3.2.3 on 2021-05-25 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0007_auto_20210525_0141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='numis_defaulti',
        ),
    ]
