# Generated by Django 3.2.3 on 2021-05-25 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0009_numis_defaulti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='numis_defaulti',
        ),
    ]
