# Generated by Django 3.2.3 on 2021-05-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0010_delete_numis_defaulti'),
    ]

    operations = [
        migrations.CreateModel(
            name='numis_def2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defaultValue', models.CharField(max_length=20)),
            ],
        ),
    ]
