# Generated by Django 3.2.3 on 2021-05-25 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0011_numis_def2'),
    ]

    operations = [
        migrations.CreateModel(
            name='defaultwerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputName', models.CharField(max_length=20)),
                ('defaultValue', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='numis_def2',
        ),
    ]
