# Generated by Django 3.2.3 on 2021-05-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numis', '0012_auto_20210525_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCookies_inDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cok_sess_id', models.CharField(max_length=100)),
                ('cok_forUnit1', models.IntegerField(max_length=2)),
                ('cok_forWahrung2', models.CharField(max_length=5)),
                ('cok_forLand3', models.CharField(max_length=50)),
                ('cok_forYear4', models.IntegerField(max_length=4)),
                ('cok_forProduce5', models.CharField(max_length=3)),
                ('cok_forEdge63', models.CharField(max_length=100)),
                ('cok_forDescrib64', models.CharField(max_length=200)),
                ('cok_forValue65', models.IntegerField(max_length=6)),
                ('cok_forPollution7', models.CharField(max_length=2)),
                ('cok_forSubmit', models.CharField(max_length=20)),
                ('cok_forPijoe', models.CharField(max_length=10)),
            ],
        ),
    ]
